### ISSUE TITLE
Актуализация email.

### ISSUE THREAD

**Issue by Shapoklyak** [oldmadjackal/DarkMed#82]
Павел, мне заморачиваться с хэшированием каких-то данных в ссылку для отправки подтверждения email или мы будем отсылать на страницу , где нужно будет ввести login и email
и при нажатии "подтверждаю" проставлять  chek_email в тбл.User ?

**Comment by oldmadjackal** [comment]
Давай, чтобы логин не светить будем какой-нить код генерить, а по нему уже привязываться.
Давай следующий раз в задаче вопросы постить - чтобы оные не плодить и в связке все было, типа :-)
