### ISSUE TITLE
Переход на другую страницу после авторизации

### ISSUE THREAD

**Issue by foreston** [oldmadjackal/DarkMed#90]
После успешной авторизации остаемся на этом же фрагменте.
Сделать автоматический переход например на карту пациента/врача.

![auth](https://cloud.githubusercontent.com/assets/18188628/14409038/0d93da02-ff14-11e5-9dde-f2f6450266de.PNG)

**Comment by oldmadjackal** [comment]
Сейчас действует следующая схема. 
**Для пациента** - если есть непрочитанные сообщения - переход на закладку "Сообщения", если нет - в Карточку пациента.
**Для врача** -  - если есть непрочитанные сообщения - переход на закладку "Сообщения", иначе остаемся в авторизации, но со списком последних обновлений.
